language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  # Instalation of the conda env
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml
  - source activate publisher
  # Installation of influxdb
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release
  - echo "deb https://repos.influxdata.com/ubuntu trusty stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt-get update
  # Install local mosquitto server
  - sudo apt-get install mosquitto
  - sudo apt-get -y install influxdb
  # Activating influx
  - sudo service influxdb start

script:
  - python -m pytest -v 