version: '2'

services:
  publisher:
      container_name: publisher
      image: encresearch/publisher:latest
      environment:
        - TOPIC # Set the environment variable before deployment
      privileged: true # Gives access to the gpio pins
      restart: unless-stopped

  watchtower: # checks for changes in the installed images (on the latest tag)
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # mounts docker socket to interact with Docker's API
    command: --interval 300 # Checks for changes every 5 minutes
    restart: unless-stopped
