version: '2'

services:
  publisher:
      container_name: publisher
      build: .
      volumes:
        - ./publisher:/app
      environment:
        - TOPIC # Set the environment variable before deployment
      privileged: true # Gives access to the gpio pins
      restart: unless-stopped
