name: publisher
dependencies:
- decorator=4.0.2=py34_0
- ipython=4.0.0=py34_0
- ipython_genutils=0.1.0=py34_0
- libgfortran=1.0=0
- numpy=1.9.2=py34_1
- openblas=0.2.14=1
- openssl=1.0.1k=1
- pandas=0.16.2=np19py34_0
- path.py=7.6.1=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=7.1.2=py34_0
- python=3.4.3=1
- python-dateutil=2.4.2=py34_0
- pytz=2015.4=py34_0
- setuptools=18.1=py34_0
- simplegeneric=0.8.1=py34_0
- six=1.9.0=py34_0
- sqlite=3.8.4.1=1
- traitlets=4.0.0=py34_0
- wheel=0.24.0=py34_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - adafruit-ads1x15==1.0.2
  - adafruit-gpio==1.0.3
  - adafruit-pureio==0.2.1
  - ipython-genutils==0.1.0
  - paho-mqtt==1.3.1
  - spidev==3.2
