name: publisher
dependecies:
- decorator= 4.4.2=py_0
- ipython= 7.13.0=py37_0
- ipython_genutils= 0.2.0=py37_0
- libgfortran= ??
- numpy= 1.18.1=py37_0
- openblas= ??
- openssl= 1.1.1g
- pandas= 1.0.3=py37_0
- path.py= 12.4.0
- pexpect= 4.8.0=py37_0
- pickleshare= 0.7.5=py37_0
- pip= 20.0.2=py37_3
- python= 3.7.7
- python-dateutil= 2.8.1=py_0
- pytz= 2020.1=py_0
- setuptools= 47.1.1=py37_0
- simplegeneric= 0.8.1=py37_2
- six= 1.15.0=py_0
- sqlite= 3.31.1
- traitlets= 4.3.3=py37_0
- wheel= ??
- xz= 5.2.5=0
- zlib= 1.2.11
- pip:
  - adafruit-ads1x15==1.0.2
  - adafruit-gpio==1.0.3
  - adafruit-pureio==0.2.1
  - ipython-genutils==0.1.0
  - paho-mqtt==1.3.1
  - spidev==3.2